spring.application.name=product-service

spring.mongodb.uri=${MONGO_URI}

# Server Configuration
server.port=${PORT}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID}

# Import secrets
spring.config.import=optional:classpath:application-secrets.properties